### ISSUE TITLE
Why emoji in https://emojihub.herokuapp.com/api/all are not in sequence.

### ISSUE THREAD

**Issue by suthargk** [cheatsnake/emojihub#1]
**Before:** 
<img width="658" alt="Screenshot 2022-04-02 at 6 54 55 PM" src="https://user-images.githubusercontent.com/43517315/162418111-f4ce8be7-749a-4101-93d3-f20e010094ab.png">

**After:** 
<img width="536" alt="Screenshot 2022-04-08 at 3 53 58 PM" src="https://user-images.githubusercontent.com/43517315/162417420-9149984e-301c-4d26-b301-7a4a6b187704.png">

**Comment by suthargk** [comment]
It was in sequence about 3 days ago but now its not in sequence.

**Comment by cheatsnake** [comment]
Thank you for your feedback. There was indeed some problem with the order of the smiles. Most likely it was because they were coming in as they were being loaded from database (whoever was fastest would be first). Then this order was cached in server's memory and remained this way for some time.

This has now been fixed and the sorting order is specified explicitly. All smileys will come in the same order - in the order they were added to the database (which corresponds to the standard order in most applications). Sorting was also fixed for categories and groups.

![image](https://user-images.githubusercontent.com/72691412/162464603-5a852117-6b4d-4b7f-a70d-6a2dd1d36e14.png)

**Comment by cheatsnake** [comment]
> It was in sequence about 3 days ago but now its not in sequence.

Thank you for your feedback. There was indeed some problem with the order of the smiles. Most likely it was because they were coming in as they were being loaded from database (whoever was fastest would be first). Then this order was cached in server's memory and remained this way for some time.

This has now been fixed and the sorting order is specified explicitly. All smileys will come in the same order - in the order they were added to the database (which corresponds to the standard order in most applications). Sorting was also fixed for categories and groups.

![image](https://user-images.githubusercontent.com/72691412/162466456-f2d77026-e54c-4446-8d0e-4c69861cdf8b.png)
